
package GUI;

import DBO.DBO_HE_DAO_TAO;
import DLL.DLL_HeDaoTao;
import MeThodShow.MyMethod;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JP_DaoTao extends javax.swing.JPanel {

    
    ArrayList<DBO_HE_DAO_TAO> lstHeDaoTao = null;
    DLL_HeDaoTao dLL_HeDaoTao = new DLL_HeDaoTao();
    MeThodShow.MyMethod method = new MyMethod();
    private DefaultTableModel dtm;
    private String dk = "";

    private static JP_DaoTao instance = null;

    public static JP_DaoTao getInstance() {
        if (instance == null) {
            instance = new JP_DaoTao();
        }
        return instance;
    }

    private JP_DaoTao() {
        initComponents();
        BiddingHeDaoTao();
    }

    public void BiddingHeDaoTao() {
        lstHeDaoTao = dLL_HeDaoTao.getAllHeDaoTao();
        Vector Column = new Vector();
        Column.add("Mã Hệ Đào Tạo");
        Column.add("Tên Hệ Đào Tạo");
        Vector data = new Vector();
        try {
            for (DBO_HE_DAO_TAO item : lstHeDaoTao) {
                Vector row = new Vector();
                row.add(item.getMaHeDaoTao());
                row.add(item.getTenHeDaoTao());
                data.add(row);
            }
        } catch (Exception e) {
            method.showMessegaWa("Error for biding HeDaoTao : " + e.toString());
        }
        tblDaoTao.setAutoCreateRowSorter(true);
        dtm = new DefaultTableModel(data, Column){
            public boolean isCellEditable(int rowCount, int columnCount){
                return false;
            }
        };
        tblDaoTao.setModel(dtm);
    }

    private void res() {
        txtMaHeDaoTao.setText("");
        txtTenHeDaoTao.setText("");
        btnUpdateDaoTao.setEnabled(false);
        btnDeleteDaoTao.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaHeDaoTao = new javax.swing.JTextField();
        txtTenHeDaoTao = new javax.swing.JTextField();
        btnAddDaoTao = new javax.swing.JButton();
        btnUpdateDaoTao = new javax.swing.JButton();
        btnDeleteDaoTao = new javax.swing.JButton();
        btnResetDaoTao = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDaoTao = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1252, 618));

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ CHƯƠNG TRÌNH ĐÀO TẠO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        jPanel2.setPreferredSize(new java.awt.Dimension(34, 14));

        jPanel3.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Mã hệ đào tạo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Tên hệ đào tạo");

        txtMaHeDaoTao.setEnabled(false);
        txtMaHeDaoTao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaHeDaoTaoKeyTyped(evt);
            }
        });

        txtTenHeDaoTao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTenHeDaoTaoKeyTyped(evt);
            }
        });

        btnAddDaoTao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddDaoTao.setForeground(new java.awt.Color(255, 51, 51));
        btnAddDaoTao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new.png"))); // NOI18N
        btnAddDaoTao.setText("Thêm");
        btnAddDaoTao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddDaoTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDaoTaoActionPerformed(evt);
            }
        });

        btnUpdateDaoTao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdateDaoTao.setForeground(new java.awt.Color(255, 51, 51));
        btnUpdateDaoTao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/save.png"))); // NOI18N
        btnUpdateDaoTao.setText("Cập nhật");
        btnUpdateDaoTao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateDaoTao.setEnabled(false);
        btnUpdateDaoTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDaoTaoActionPerformed(evt);
            }
        });

        btnDeleteDaoTao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDeleteDaoTao.setForeground(new java.awt.Color(255, 51, 51));
        btnDeleteDaoTao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Remove.png"))); // NOI18N
        btnDeleteDaoTao.setText("Xóa");
        btnDeleteDaoTao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteDaoTao.setEnabled(false);
        btnDeleteDaoTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDaoTaoActionPerformed(evt);
            }
        });

        btnResetDaoTao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnResetDaoTao.setForeground(new java.awt.Color(255, 51, 51));
        btnResetDaoTao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/reset.png"))); // NOI18N
        btnResetDaoTao.setText("Làm mới");
        btnResetDaoTao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetDaoTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetDaoTaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenHeDaoTao)
                    .addComponent(txtMaHeDaoTao, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddDaoTao)
                .addGap(20, 20, 20)
                .addComponent(btnUpdateDaoTao)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteDaoTao)
                .addGap(13, 13, 13)
                .addComponent(btnResetDaoTao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaHeDaoTao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenHeDaoTao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDaoTao)
                    .addComponent(btnUpdateDaoTao)
                    .addComponent(btnDeleteDaoTao)
                    .addComponent(btnResetDaoTao))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel5.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        tblDaoTao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDaoTao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDaoTaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDaoTao);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1252, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDaoTaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDaoTaoMouseClicked
        int row = tblDaoTao.getSelectedRow();
        txtMaHeDaoTao.setEnabled(false);
        lstHeDaoTao = dLL_HeDaoTao.getAllHeDaoTao();
        txtMaHeDaoTao.setText(lstHeDaoTao.get(row).getMaHeDaoTao());
        txtTenHeDaoTao.setText(lstHeDaoTao.get(row).getTenHeDaoTao());
        btnUpdateDaoTao.setEnabled(true);
        btnDeleteDaoTao.setEnabled(true);
        dk = lstHeDaoTao.get(row).getMaHeDaoTao();
    }//GEN-LAST:event_tblDaoTaoMouseClicked

    private void btnResetDaoTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetDaoTaoActionPerformed
        res();
    }//GEN-LAST:event_btnResetDaoTaoActionPerformed

    private void btnDeleteDaoTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDaoTaoActionPerformed
        int yes = JOptionPane.showConfirmDialog(null, "Bạn Muốn Xóa Dữ Liệu ?", "Thông Báo", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (yes == JOptionPane.YES_OPTION) {
            String ma = txtMaHeDaoTao.getText();
            if (ma.isEmpty()) {
                method.showMessegaNo("MaHeDaoTao is Empty");
            } else if (dLL_HeDaoTao.Delete(ma)) {
                method.showMessegaNo("Xóa Thành Công !");
                BiddingHeDaoTao();
                res();
            } else {
                method.showMessegaNo("Xóa Thất Bại !");
            }
        }
    }//GEN-LAST:event_btnDeleteDaoTaoActionPerformed

    private void btnAddDaoTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDaoTaoActionPerformed
        String ma = txtMaHeDaoTao.getText();
        txtMaHeDaoTao.requestFocus();
        txtMaHeDaoTao.setEnabled(true);
        String ten = txtTenHeDaoTao.getText();
        lstHeDaoTao = dLL_HeDaoTao.Check_HeDaoTao(ma);
        if (ma.isEmpty() || ten.isEmpty()) {
            method.showMessegaNo("Bạn Cần Nhập Đầy Đủ Thông Tin !");
        } else if (lstHeDaoTao.size() > 0) {
            method.showMessegaWa("Đã Tồn Tại Hệ Đào Tạo Này, Bạn Không Thể Thêm Vào Nữa");
            res();
        } else {
            DBO_HE_DAO_TAO obj = new DBO_HE_DAO_TAO();
            obj.setMaHeDaoTao(ma);
            obj.setTenHeDaoTao(ten);
            if (dLL_HeDaoTao.Insert(obj)) {
                method.showMessegaNo("Thêm Thành Công !");
                BiddingHeDaoTao();
            } else {
                method.showMessegaNo("Thêm Thất Bại !");
            }
        }
    }//GEN-LAST:event_btnAddDaoTaoActionPerformed

    private void btnUpdateDaoTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDaoTaoActionPerformed
        String ma = txtMaHeDaoTao.getText();
        String ten = txtTenHeDaoTao.getText();
        if (ma.isEmpty() || ten.isEmpty()) {
            method.showMessegaNo("Bạn Cần Nhập Đầy Đủ Thông Tin !");
        } else {
            DBO_HE_DAO_TAO obj = new DBO_HE_DAO_TAO();
            obj.setMaHeDaoTao(ma);
            obj.setTenHeDaoTao(ten);
            if (dLL_HeDaoTao.Update(obj, dk)) {
                method.showMessegaNo("Cập Nhật Thành Công !");
                BiddingHeDaoTao();
                res();
            } else {
                method.showMessegaNo("Cập Nhật Thất Bại !");
            }
        }
    }//GEN-LAST:event_btnUpdateDaoTaoActionPerformed

    private void txtMaHeDaoTaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaHeDaoTaoKeyTyped
        if (txtMaHeDaoTao.getText().length() >= 5) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtMaHeDaoTaoKeyTyped

    private void txtTenHeDaoTaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenHeDaoTaoKeyTyped
        if (txtTenHeDaoTao.getText().length() >= 30) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtTenHeDaoTaoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDaoTao;
    private javax.swing.JButton btnDeleteDaoTao;
    private javax.swing.JButton btnResetDaoTao;
    private javax.swing.JButton btnUpdateDaoTao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDaoTao;
    private javax.swing.JTextField txtMaHeDaoTao;
    private javax.swing.JTextField txtTenHeDaoTao;
    // End of variables declaration//GEN-END:variables
}
